# R_010 — NumPy Basics (Reproducible)

Purpose: reproduce key NumPy operations from the note.  
Outputs: small arrays + sanity prints (shape/dtype) + simple plot.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

print("numpy:", np.__version__)

numpy: 2.2.6


In [3]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

print("a:", a, "shape=", a.shape, "dtype=", a.dtype)
print("b:\n", b, "\nshape=", b.shape, "dtype=", b.dtype)

zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
ar = np.arange(0, 10, 2)

print("zeros:\n", zeros)
print("ones:\n", ones)
print("arange:", ar)

a: [1 2 3] shape= (3,) dtype= int64
b:
 [[1. 2. 3.]
 [4. 5. 6.]] 
shape= (2, 3) dtype= float64
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
arange: [0 2 4 6 8]


In [ ]:
x = np.arange(1, 13).reshape(3, 4)
print("x:\n", x)

print("x[0, :]:", x[0, :])
print("x[:, 2]:", x[:, 2])
print("x[1:, 1:3]:\n", x[1:, 1:3])